server:
  port: 8900
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2021?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: 124.223.78.24
    port: 6379
    database: 0
    connect-timeout: 1800000
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 5
        min-idle: 0
    password: JP1R5MAR3Orh